### ISSUE TITLE
include more energy sources besides solar and wind (biomass, coal, nuclear, etc.)

### ISSUE THREAD

**Issue by Sebaristoteles** [Sebaristoteles/sposm_group_assignment#8]
extends the data kept for the Shiny App and adds some more options to the Shiny App

**Comment by Sebaristoteles** [comment]
use different colors in Shiny
- biomass: should be green (change color of solar to yellow)
- coal: grey-black
- brown coal: bright brown - dark brown
- nuclear: green - neon-green (from a normal green to a very bright and shining green?)

**Comment by yagmurdalman** [comment]
Hey,
I added

Verbrennung - Coal Energy
Biomasse -  Biomass Energy
Wasser - Water Energy
Geothermie - Geothermal Energy.

However, I can’t see Nuclear Energy and Brown Coal Energy in the data set and can’t figure out how to add the following energy types:

Gaserzeugungseinheit - Gas generation unit
Gasverbrauchseinheit - Gas consumption unit
Gasspeichereinheit - Gas storage unit
Stromspeichereinheit - Electricity storage unit
Stromverbrauchseinheit - Electricity consumption unit

Do you have any suggestion?

**Comment by Sebaristoteles** [comment]
The app looks amazing already!

I can't find nuclear energy either in the data source. I think it's not integrated.
For the other types, I think that electricity storage units would be very interesting (different yellows in displaying?). Their number should increase in the last and coming years.
The other gas facilities do not have information on power, so just the number would be interesting. But I would rather differentiate the combustion "Verbrennung" by using the variable "Energietraeger" in "2.select_data.R". After loading "enh2" you could use the variable "Energietraeger" to rename "EinheitenTyp" in brown coal (Braunkohle), black coal (Steinkohle) and gas ('Erdgas' + 'andere Gase'). The greys as color is fine while for brown coal 'brown' would be even nicer.

**Comment by Sebaristoteles** [comment]
Obviously, after splitting the combustion category, the calculation of the processed data has to be done again. By renaming "EinheitenTyp" it should not be necessary to do more in code changes for the calculation, I think.
