### ISSUE TITLE
provide the user the possibility to choose the number of categories in the legend

### ISSUE THREAD

**Issue by Sebaristoteles** [Sebaristoteles/sposm_group_assignment#9]
Add a "sliderInput" that starts at 10 and has a range from to 15
https://shiny.rstudio.com/reference/shiny/0.14/sliderInput.html

The number to choose should be "n" in tmap

**Comment by Sebaristoteles** [comment]
That's what I expected!
I am just puzzled why it is not possible to choose the exact number of categories.

**Comment by fengzhi22** [comment]
The number of categories is automatically calculated by tm_polygons and for now I don't see a way to make it a fixed number. This article (https://geocompr.github.io/post/2019/tmap-color-scales/) explains that "importantly, not every n is possible depending on the range of the values in the data."

**Comment by Sebaristoteles** [comment]
Okay, then let's stick with this solution.

**Comment by Sebaristoteles** [comment]
Long done
